package models

import (
	"time"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

// AvExeTask represents a task within an aircraft work package
type AvExeTask struct {
	ODataEtag                string                `bson:"@odata.etag,omitempty" json:"@odata.etag,omitempty"`
	Luname                   string                `bson:"luname,omitempty" json:"luname,omitempty"`
	Keyref                   string                `bson:"keyref,omitempty" json:"keyref,omitempty"`
	Objsite                  string                `bson:"Objsite,omitempty" json:"Objsite,omitempty"`
	Objstate                 string                `bson:"Objstate,omitempty" json:"Objstate,omitempty"`
	Objgrants                *string               `bson:"Objgrants,omitempty" json:"Objgrants,omitempty"`
	TaskSeq                  int                   `bson:"TaskSeq,omitempty" json:"TaskSeq,omitempty"`
	OrderNo                  int                   `bson:"OrderNo,omitempty" json:"OrderNo,omitempty"`
	Site                     string                `bson:"Site,omitempty" json:"Site,omitempty"`
	Company                  string                `bson:"Company,omitempty" json:"Company,omitempty"`
	PriorityId               *int                  `bson:"PriorityId,omitempty" json:"PriorityId,omitempty"`
	WorkTypeId               *int                  `bson:"WorkTypeId,omitempty" json:"WorkTypeId,omitempty"`
	Description              string                `bson:"Description,omitempty" json:"Description,omitempty"`
	LongDescription          *string               `bson:"LongDescription,omitempty" json:"LongDescription,omitempty"`
	CreatedBy                string                `bson:"CreatedBy,omitempty" json:"CreatedBy,omitempty"`
	CreatedDate              *time.Time            `bson:"CreatedDate,omitempty" json:"CreatedDate,omitempty"`
	ReportedBy               string                `bson:"ReportedBy,omitempty" json:"ReportedBy,omitempty"`
	ReportedDate             *time.Time            `bson:"ReportedDate,omitempty" json:"ReportedDate,omitempty"`
	PlannedStart             *time.Time            `bson:"PlannedStart,omitempty" json:"PlannedStart,omitempty"`
	PlannedFinish            *time.Time            `bson:"PlannedFinish,omitempty" json:"PlannedFinish,omitempty"`
	Duration                 *int                  `bson:"Duration,omitempty" json:"Duration,omitempty"`
	ActualStart              *time.Time            `bson:"ActualStart,omitempty" json:"ActualStart,omitempty"`
	ActualFinish             *time.Time            `bson:"ActualFinish,omitempty" json:"ActualFinish,omitempty"`
	EarliestStart            *time.Time            `bson:"EarliestStart,omitempty" json:"EarliestStart,omitempty"`
	LatestStart              *time.Time            `bson:"LatestStart,omitempty" json:"LatestStart,omitempty"`
	LatestFinish             *time.Time            `bson:"LatestFinish,omitempty" json:"LatestFinish,omitempty"`
	FixedStart               *time.Time            `bson:"FixedStart,omitempty" json:"FixedStart,omitempty"`
	ExcludeFromScheduling    bool                  `bson:"ExcludeFromScheduling,omitempty" json:"ExcludeFromScheduling,omitempty"`
	AdjustedDuration         bool                  `bson:"AdjustedDuration,omitempty" json:"AdjustedDuration,omitempty"`
	Remark                   *string               `bson:"Remark,omitempty" json:"Remark,omitempty"`
	InternalRemark           *string               `bson:"InternalRemark,omitempty" json:"InternalRemark,omitempty"`
	ActionTaken              *string               `bson:"ActionTaken,omitempty" json:"ActionTaken,omitempty"`
	CancelCause              *string               `bson:"CancelCause,omitempty" json:"CancelCause,omitempty"`
	SourceConnectionLuName   *string               `bson:"SourceConnectionLuName,omitempty" json:"SourceConnectionLuName,omitempty"`
	SourceConnectionRowkey   *string               `bson:"SourceConnectionRowkey,omitempty" json:"SourceConnectionRowkey,omitempty"`
	ReportedConnectionType   *string               `bson:"ReportedConnectionType,omitempty" json:"ReportedConnectionType,omitempty"`
	ReportedObjConnLuName    *string               `bson:"ReportedObjConnLuName,omitempty" json:"ReportedObjConnLuName,omitempty"`
	ReportedObjConnRowkey    *string               `bson:"ReportedObjConnRowkey,omitempty" json:"ReportedObjConnRowkey,omitempty"`
	ActualConnectionType     *string               `bson:"ActualConnectionType,omitempty" json:"ActualConnectionType,omitempty"`
	ActualObjConnLuName      *string               `bson:"ActualObjConnLuName,omitempty" json:"ActualObjConnLuName,omitempty"`
	ActualObjConnRowkey      *string               `bson:"ActualObjConnRowkey,omitempty" json:"ActualObjConnRowkey,omitempty"`
	TestPointSeq             *int                  `bson:"TestPointSeq,omitempty" json:"TestPointSeq,omitempty"`
	CustomerNo               *string               `bson:"CustomerNo,omitempty" json:"CustomerNo,omitempty"`
	PreAccountingId          int                   `bson:"PreAccountingId,omitempty" json:"PreAccountingId,omitempty"`
	NoteId                   int                   `bson:"NoteId,omitempty" json:"NoteId,omitempty"`
	SourceRef1               *string               `bson:"SourceRef1,omitempty" json:"SourceRef1,omitempty"`
	SourceRef2               *string               `bson:"SourceRef2,omitempty" json:"SourceRef2,omitempty"`
	SourceRef3               *string               `bson:"SourceRef3,omitempty" json:"SourceRef3,omitempty"`
	SourceRef4               *string               `bson:"SourceRef4,omitempty" json:"SourceRef4,omitempty"`
	MasterTaskSeq            *int                  `bson:"MasterTaskSeq,omitempty" json:"MasterTaskSeq,omitempty"`
	DuplicateType            *string               `bson:"DuplicateType,omitempty" json:"DuplicateType,omitempty"`
	CostCode                 *string               `bson:"CostCode,omitempty" json:"CostCode,omitempty"`
	ActivitySeq              *int                  `bson:"ActivitySeq,omitempty" json:"ActivitySeq,omitempty"`
	ReportProjPlannedCost    string                `bson:"ReportProjPlannedCost,omitempty" json:"ReportProjPlannedCost,omitempty"`
	MobileTaskId             *string               `bson:"MobileTaskId,omitempty" json:"MobileTaskId,omitempty"`
	ChangedDate              *time.Time            `bson:"ChangedDate,omitempty" json:"ChangedDate,omitempty"`
	AllowMultipleVisits      bool                  `bson:"AllowMultipleVisits,omitempty" json:"AllowMultipleVisits,omitempty"`
	MinVisitDuration         *int                  `bson:"MinVisitDuration,omitempty" json:"MinVisitDuration,omitempty"`
	SplitMinPriority         *int                  `bson:"SplitMinPriority,omitempty" json:"SplitMinPriority,omitempty"`
	InterruptPriority        *int                  `bson:"InterruptPriority,omitempty" json:"InterruptPriority,omitempty"`
	InterruptMultiplier      *int                  `bson:"InterruptMultiplier,omitempty" json:"InterruptMultiplier,omitempty"`
	Interrupt                *bool                 `bson:"Interrupt,omitempty" json:"Interrupt,omitempty"`
	ActivityTypeId           *int                  `bson:"ActivityTypeId,omitempty" json:"ActivityTypeId,omitempty"`
	DisplacementPriority     *int                  `bson:"DisplacementPriority,omitempty" json:"DisplacementPriority,omitempty"`
	DatasetId                *int                  `bson:"DatasetId,omitempty" json:"DatasetId,omitempty"`
	ExternalId               *string               `bson:"ExternalId,omitempty" json:"ExternalId,omitempty"`
	CreatedDateOfs           float64               `bson:"CreatedDateOfs,omitempty" json:"CreatedDateOfs,omitempty"`
	ReportedDateOfs          float64               `bson:"ReportedDateOfs,omitempty" json:"ReportedDateOfs,omitempty"`
	PlannedStartOfs          *float64              `bson:"PlannedStartOfs,omitempty" json:"PlannedStartOfs,omitempty"`
	PlannedFinishOfs         *float64              `bson:"PlannedFinishOfs,omitempty" json:"PlannedFinishOfs,omitempty"`
	ActualStartOfs           *float64              `bson:"ActualStartOfs,omitempty" json:"ActualStartOfs,omitempty"`
	ActualFinishOfs          *float64              `bson:"ActualFinishOfs,omitempty" json:"ActualFinishOfs,omitempty"`
	EarliestStartOfs         float64               `bson:"EarliestStartOfs,omitempty" json:"EarliestStartOfs,omitempty"`
	LatestStartOfs           *float64              `bson:"LatestStartOfs,omitempty" json:"LatestStartOfs,omitempty"`
	LatestFinishOfs          float64               `bson:"LatestFinishOfs,omitempty" json:"LatestFinishOfs,omitempty"`
	FixedStartOfs            *float64              `bson:"FixedStartOfs,omitempty" json:"FixedStartOfs,omitempty"`
	ChangedDateOfs           float64               `bson:"ChangedDateOfs,omitempty" json:"ChangedDateOfs,omitempty"`
	CustomMetricId           *int                  `bson:"CustomMetricId,omitempty" json:"CustomMetricId,omitempty"`
	CustomMetricValue        *float64              `bson:"CustomMetricValue,omitempty" json:"CustomMetricValue,omitempty"`
	AppointmentRequired      bool                  `bson:"AppointmentRequired,omitempty" json:"AppointmentRequired,omitempty"`
	WarrantyAssessmentId     *int                  `bson:"WarrantyAssessmentId,omitempty" json:"WarrantyAssessmentId,omitempty"`
	WarrantyRemark           *string               `bson:"WarrantyRemark,omitempty" json:"WarrantyRemark,omitempty"`
	RemotelyFulfilled        bool                  `bson:"RemotelyFulfilled,omitempty" json:"RemotelyFulfilled,omitempty"`
	ScheduledManually        bool                  `bson:"ScheduledManually,omitempty" json:"ScheduledManually,omitempty"`
	WtBiTimestamp            *time.Time            `bson:"WtBiTimestamp,omitempty" json:"WtBiTimestamp,omitempty"`
	AircraftId               int                   `bson:"AircraftId,omitempty" json:"AircraftId,omitempty"`
	FaultId                  int                   `bson:"FaultId,omitempty" json:"FaultId,omitempty"`
	ClassCode                string                `bson:"ClassCode,omitempty" json:"ClassCode,omitempty"`
	SubclassCode             *string               `bson:"SubclassCode,omitempty" json:"SubclassCode,omitempty"`
	TaskCode                 *string               `bson:"TaskCode,omitempty" json:"TaskCode,omitempty"`
	IsHistoric               *bool                 `bson:"IsHistoric,omitempty" json:"IsHistoric,omitempty"`
	AircraftWpId             int                   `bson:"AircraftWpId,omitempty" json:"AircraftWpId,omitempty"`
	Barcode                  string                `bson:"Barcode,omitempty" json:"Barcode,omitempty"`
	MxUniqueKey              *string               `bson:"MxUniqueKey,omitempty" json:"MxUniqueKey,omitempty"`
	ConfigPosition           string                `bson:"ConfigPosition,omitempty" json:"ConfigPosition,omitempty"`
	AltId                    string                `bson:"AltId,omitempty" json:"AltId,omitempty"`
	CompletedBy              *string               `bson:"CompletedBy,omitempty" json:"CompletedBy,omitempty"`
	IsMobileClientRequest    *bool                 `bson:"IsMobileClientRequest,omitempty" json:"IsMobileClientRequest,omitempty"`
	RequestStateCd           *string               `bson:"RequestStateCd,omitempty" json:"RequestStateCd,omitempty"`
	RequestCorrelationId     *string               `bson:"RequestCorrelationId,omitempty" json:"RequestCorrelationId,omitempty"`
	RequestErrorMessage      *string               `bson:"RequestErrorMessage,omitempty" json:"RequestErrorMessage,omitempty"`
	RequestUri               *string               `bson:"RequestUri,omitempty" json:"RequestUri,omitempty"`
	RequestOperation         *string               `bson:"RequestOperation,omitempty" json:"RequestOperation,omitempty"`
	BindSignatureId          string                `bson:"BindSignatureId,omitempty" json:"BindSignatureId,omitempty"`
	StartedUser              *string               `bson:"StartedUser,omitempty" json:"StartedUser,omitempty"`
	PrevAircraftWpId         *int                  `bson:"PrevAircraftWpId,omitempty" json:"PrevAircraftWpId,omitempty"`
	ApprovalNumber           *string               `bson:"ApprovalNumber,omitempty" json:"ApprovalNumber,omitempty"`
	CompletionNote           *string               `bson:"CompletionNote,omitempty" json:"CompletionNote,omitempty"`
	Location                 *string               `bson:"Location,omitempty" json:"Location,omitempty"`
	IsRoutine                bool                  `bson:"IsRoutine,omitempty" json:"IsRoutine,omitempty"`
	CrewCode                 *string               `bson:"CrewCode,omitempty" json:"CrewCode,omitempty"`
	CrewName                 *string               `bson:"CrewName,omitempty" json:"CrewName,omitempty"`
	MaterialAvailUserStatus  *string               `bson:"MaterialAvailUserStatus,omitempty" json:"MaterialAvailUserStatus,omitempty"`
	EtopsSignificant         bool                  `bson:"EtopsSignificant,omitempty" json:"EtopsSignificant,omitempty"`
	FlightSafetyImpact       bool                  `bson:"FlightSafetyImpact,omitempty" json:"FlightSafetyImpact,omitempty"`
	HmContractId             *string               `bson:"HmContractId,omitempty" json:"HmContractId,omitempty"`
	HmContractLineNo         *int                  `bson:"HmContractLineNo,omitempty" json:"HmContractLineNo,omitempty"`
	JtExecutionInstanceArray []JtExecutionInstance `bson:"JtExecutionInstanceArray,omitempty" json:"JtExecutionInstanceArray,omitempty"`
}

// JtExecutionInstance represents an execution instance within a task
type JtExecutionInstance struct {
	TaskSeq                int        `bson:"TaskSeq,omitempty" json:"TaskSeq,omitempty"`
	ExecutionInstanceSeq   int        `bson:"ExecutionInstanceSeq,omitempty" json:"ExecutionInstanceSeq,omitempty"`
	CreatedDate            *time.Time `bson:"CreatedDate,omitempty" json:"CreatedDate,omitempty"`
	TaskResourceSeq        int        `bson:"TaskResourceSeq,omitempty" json:"TaskResourceSeq,omitempty"`
	AllocatedHours         *float64   `bson:"AllocatedHours,omitempty" json:"AllocatedHours,omitempty"`
	CreatedBy              string     `bson:"CreatedBy,omitempty" json:"CreatedBy,omitempty"`
	ResourceSeq            int        `bson:"ResourceSeq,omitempty" json:"ResourceSeq,omitempty"`
	AssignmentStart        *time.Time `bson:"AssignmentStart,omitempty" json:"AssignmentStart,omitempty"`
	AssignmentFinish       *time.Time `bson:"AssignmentFinish,omitempty" json:"AssignmentFinish,omitempty"`
	AllocatedStart         *time.Time `bson:"AllocatedStart,omitempty" json:"AllocatedStart,omitempty"`
	AllocatedFinish        *time.Time `bson:"AllocatedFinish,omitempty" json:"AllocatedFinish,omitempty"`
	FixedStart             *time.Time `bson:"FixedStart,omitempty" json:"FixedStart,omitempty"`
	FixedResource          bool       `bson:"FixedResource,omitempty" json:"FixedResource,omitempty"`
	ResourceActivitySeq    int        `bson:"ResourceActivitySeq,omitempty" json:"ResourceActivitySeq,omitempty"`
	ResourceActAllocSeq    int        `bson:"ResourceActAllocSeq,omitempty" json:"ResourceActAllocSeq,omitempty"`
	CancelCause            *string    `bson:"CancelCause,omitempty" json:"CancelCause,omitempty"`
	IncompletionCause      *string    `bson:"IncompletionCause,omitempty" json:"IncompletionCause,omitempty"`
	TaskLeader             bool       `bson:"TaskLeader,omitempty" json:"TaskLeader,omitempty"`
	SentDate               *time.Time `bson:"SentDate,omitempty" json:"SentDate,omitempty"`
	DownloadedDate         *time.Time `bson:"DownloadedDate,omitempty" json:"DownloadedDate,omitempty"`
	WorkStart              *time.Time `bson:"WorkStart,omitempty" json:"WorkStart,omitempty"`
	WorkFinish             *time.Time `bson:"WorkFinish,omitempty" json:"WorkFinish,omitempty"`
	VisitId                int        `bson:"VisitId,omitempty" json:"VisitId,omitempty"`
	ModifiedTimeToComplete *float64   `bson:"ModifiedTimeToComplete,omitempty" json:"ModifiedTimeToComplete,omitempty"`
	TimeToCompletion       *float64   `bson:"TimeToCompletion,omitempty" json:"TimeToCompletion,omitempty"`
	ChangedDate            *time.Time `bson:"ChangedDate,omitempty" json:"ChangedDate,omitempty"`
	Origin                 string     `bson:"Origin,omitempty" json:"Origin,omitempty"`
	FollowOnVisits         bool       `bson:"FollowOnVisits,omitempty" json:"FollowOnVisits,omitempty"`
	TimeToCompleteUpdated  *time.Time `bson:"TimeToCompleteUpdated,omitempty" json:"TimeToCompleteUpdated,omitempty"`
	ActualWorkedHours      *float64   `bson:"ActualWorkedHours,omitempty" json:"ActualWorkedHours,omitempty"`
	ActionTaken            *string    `bson:"ActionTaken,omitempty" json:"ActionTaken,omitempty"`
	AdjustToSchedule       string     `bson:"AdjustToSchedule,omitempty" json:"AdjustToSchedule,omitempty"`
	Highlight              *string    `bson:"Highlight,omitempty" json:"Highlight,omitempty"`
	ExpectedArrivalTime    *time.Time `bson:"ExpectedArrivalTime,omitempty" json:"ExpectedArrivalTime,omitempty"`
	CreatedDateOfs         float64    `bson:"CreatedDateOfs,omitempty" json:"CreatedDateOfs,omitempty"`
	AssignmentStartOfs     *float64   `bson:"AssignmentStartOfs,omitempty" json:"AssignmentStartOfs,omitempty"`
	AssignmentFinishOfs    *float64   `bson:"AssignmentFinishOfs,omitempty" json:"AssignmentFinishOfs,omitempty"`
	AllocatedStartOfs      *float64   `bson:"AllocatedStartOfs,omitempty" json:"AllocatedStartOfs,omitempty"`
	AllocatedFinishOfs     *float64   `bson:"AllocatedFinishOfs,omitempty" json:"AllocatedFinishOfs,omitempty"`
	FixedStartOfs          *float64   `bson:"FixedStartOfs,omitempty" json:"FixedStartOfs,omitempty"`
	SentDateOfs            *float64   `bson:"SentDateOfs,omitempty" json:"SentDateOfs,omitempty"`
	DownloadedDateOfs      *float64   `bson:"DownloadedDateOfs,omitempty" json:"DownloadedDateOfs,omitempty"`
	WorkStartOfs           *float64   `bson:"WorkStartOfs,omitempty" json:"WorkStartOfs,omitempty"`
	WorkFinishOfs          *float64   `bson:"WorkFinishOfs,omitempty" json:"WorkFinishOfs,omitempty"`
	ChangedDateOfs         *float64   `bson:"ChangedDateOfs,omitempty" json:"ChangedDateOfs,omitempty"`
	TimeToCompleteUpdOfs   *float64   `bson:"TimeToCompleteUpdOfs,omitempty" json:"TimeToCompleteUpdOfs,omitempty"`
	ExpectedArrivalTimeOfs *float64   `bson:"ExpectedArrivalTimeOfs,omitempty" json:"ExpectedArrivalTimeOfs,omitempty"`
}

// AircraftWorkPackage represents the main aircraft work package document
type AircraftWorkPackage struct {
	ID                     primitive.ObjectID `bson:"_id,omitempty" json:"_id,omitempty"`
	ODataEtag              string             `bson:"@odata.etag,omitempty" json:"@odata.etag,omitempty"`
	Luname                 string             `bson:"luname,omitempty" json:"luname,omitempty"`
	Keyref                 string             `bson:"keyref,omitempty" json:"keyref,omitempty"`
	Objstate               string             `bson:"Objstate,omitempty" json:"Objstate,omitempty"`
	Objgrants              *string            `bson:"Objgrants,omitempty" json:"Objgrants,omitempty"`
	AircraftWorkPackageId  int                `bson:"AircraftWorkPackageId,omitempty" json:"AircraftWorkPackageId,omitempty"`
	AircraftId             int                `bson:"AircraftId,omitempty" json:"AircraftId,omitempty"`
	LocationCode           string             `bson:"LocationCode,omitempty" json:"LocationCode,omitempty"`
	WorkPackageName        string             `bson:"WorkPackageName,omitempty" json:"WorkPackageName,omitempty"`
	WoNumber               string             `bson:"WoNumber,omitempty" json:"WoNumber,omitempty"`
	IsHistoric             bool               `bson:"IsHistoric,omitempty" json:"IsHistoric,omitempty"`
	SchedStartDateTime     *time.Time         `bson:"SchedStartDateTime,omitempty" json:"SchedStartDateTime,omitempty"`
	SchedEndDateTime       *time.Time         `bson:"SchedEndDateTime,omitempty" json:"SchedEndDateTime,omitempty"`
	ActualStartDateTime    *time.Time         `bson:"ActualStartDateTime,omitempty" json:"ActualStartDateTime,omitempty"`
	ActualEndDateTime      *time.Time         `bson:"ActualEndDateTime,omitempty" json:"ActualEndDateTime,omitempty"`
	IsReleaseToService     *bool              `bson:"IsReleaseToService,omitempty" json:"IsReleaseToService,omitempty"`
	MxUniqueKey            string             `bson:"MxUniqueKey,omitempty" json:"MxUniqueKey,omitempty"`
	Barcode                string             `bson:"Barcode,omitempty" json:"Barcode,omitempty"`
	SignedUser             *string            `bson:"SignedUser,omitempty" json:"SignedUser,omitempty"`
	AltId                  string             `bson:"AltId,omitempty" json:"AltId,omitempty"`
	Duration               float64            `bson:"Duration,omitempty" json:"Duration,omitempty"`
	NoOfAssignedTasks      int                `bson:"NoOfAssignedTasks,omitempty" json:"NoOfAssignedTasks,omitempty"`
	RequestStateCd         *string            `bson:"RequestStateCd,omitempty" json:"RequestStateCd,omitempty"`
	RequestCorrelationId   *string            `bson:"RequestCorrelationId,omitempty" json:"RequestCorrelationId,omitempty"`
	IsMobileClientRequest  *bool              `bson:"IsMobileClientRequest,omitempty" json:"IsMobileClientRequest,omitempty"`
	RqstFailedTasksStatus  *string            `bson:"RqstFailedTasksStatus,omitempty" json:"RqstFailedTasksStatus,omitempty"`
	RequestErrorMessage    *string            `bson:"RequestErrorMessage,omitempty" json:"RequestErrorMessage,omitempty"`
	RequestUri             *string            `bson:"RequestUri,omitempty" json:"RequestUri,omitempty"`
	RequestOperation       *string            `bson:"RequestOperation,omitempty" json:"RequestOperation,omitempty"`
	ExternalId             string             `bson:"ExternalId,omitempty" json:"ExternalId,omitempty"`
	MessageDate            *time.Time         `bson:"MessageDate,omitempty" json:"MessageDate,omitempty"`
	StatusBeforeStart      *string            `bson:"StatusBeforeStart,omitempty" json:"StatusBeforeStart,omitempty"`
	IsHeavyMaintenance     bool               `bson:"IsHeavyMaintenance,omitempty" json:"IsHeavyMaintenance,omitempty"`
	HmContractId           *string            `bson:"HmContractId,omitempty" json:"HmContractId,omitempty"`
	CustomerNo             *string            `bson:"CustomerNo,omitempty" json:"CustomerNo,omitempty"`
	LastClearWorkscopeDate *time.Time         `bson:"LastClearWorkscopeDate,omitempty" json:"LastClearWorkscopeDate,omitempty"`
	BindSignatureId        string             `bson:"BindSignatureId,omitempty" json:"BindSignatureId,omitempty"`
	Avexetask              []AvExeTask        `bson:"AvTaskArray,omitempty" json:"AvTaskArray,omitempty"`
}
